Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  FileNotFoundError: [Errno 2] No such file or directory: './data/ihdp_npci_1-100.train.npz'
Run `reticulate::py_last_error()` for details.
Warning message:
In fwrite(sim_results, paste0("~/DRinference/simResultsDR/sim_results_",  :
  Input has no columns; doing nothing.
If you intended to overwrite the file at /home/lvanderl/DRinference/simResultsDR/sim_results_ihdp.csv with an empty one, please use file.remove first.
